services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - TZ=Asia/Tbilisi
      #- MONGODB_LOG_VERBOSITY: "0"
    ports:
      - "127.0.0.1:5050:27017"
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db

  python_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: wb-python-app:1.0
    container_name: python_app
    depends_on:
      - mongodb
    environment:
      - TZ=Asia/Tbilisi
      - DB_NAME=${DB_NAME}
      - MONGO_URI=${MONGO_URI}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - DAYS_BACK=${DAYS_BACK}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_SERVICE_ACCOUNT_FILE=${GOOGLE_SERVICE_ACCOUNT_FILE}
      - WB_API_TOKEN_FILE=${WB_API_TOKEN_FILE}
      - WB_API_TOKEN=$(cat ${WB_API_TOKEN_FILE})
    ports:
      - "5678:5678"
    volumes:
      - ./app:/usr/src/app
      - ./secrets:/usr/src/app/secrets:ro
#    command: ["/bin/bash", "-c", "python app.py"] # && docker-compose down"]



#  dbbrowser:
#    image: mongo-express
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
#    depends_on:
#      - mongodb
  #nginx:
  #  build:
  #    context: ./nginx
  #    dockerfile: Dockerfile.nginx
  #  image: nginx:1.27.1-bookworm
  #  container_name: nginx
  #  ports:
  #    - "8985:8985"
  #  depends_on:
  #    - python_app
