FROM python:3.12-slim-bookworm

ENV TZ=Asia/Tbilisi
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y docker-compose
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY .env ${WORKDIR}
CMD ["python", "app.py"]
